// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoDIExample.DataLayer;

#nullable disable

namespace NoDIExample.DataLayer.Migrations
{
    [DbContext(typeof(CommerceContext))]
    [Migration("20220513092343_AddDataSeed")]
    partial class AddDataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NoDIExample.DataLayer.Entities.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("320cb512-92b5-4d49-8801-885873437055"),
                            Description = "This is product 1",
                            IsFeatured = true,
                            Name = "Product 1",
                            UnitPrice = 5000m
                        },
                        new
                        {
                            Id = new Guid("dd5924fe-8707-4e4a-84c6-b827b98463b0"),
                            Description = "This is product 2",
                            IsFeatured = true,
                            Name = "Product 2",
                            UnitPrice = 3000m
                        },
                        new
                        {
                            Id = new Guid("58ce934b-f92b-4504-97bf-988cf16c101c"),
                            Description = "This is product 3",
                            IsFeatured = false,
                            Name = "Product 3",
                            UnitPrice = 2500m
                        },
                        new
                        {
                            Id = new Guid("5d277e67-63ea-41f8-9e00-441b90245977"),
                            Description = "This is product 4",
                            IsFeatured = true,
                            Name = "Product 4",
                            UnitPrice = 7500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
